import 'rsuite/dist/rsuite.min.css';
import '@/styles/rs-custom.globals.scss';
import '@/styles/globals.scss';
import { Provider } from '@/app/Provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // テーマのチラつきを抑えるために指定
  const className = 'rs-theme-dark';

  return (
    <html lang="en">
      <body className={className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
